# Generated by Django 5.2 on 2025-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_price_alter_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='app1.ProductCategory', to='app1.category'),
        ),
    ]
