# Generated by Django 5.2 on 2025-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='app1.ProductCategory', to='app1.category'),
        ),
    ]
